'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, Plus, Send, Paperclip, X, Download, Leaf, Sparkles, LogOut, FileText } from 'lucide-react';
import Markdown from 'react-markdown';
import { supabase } from '../lib/browser';
import { Attachment, MAX_BODY, MAX_FILE, validateAttachments } from '../lib/limits';
type Message={role:'user'|'assistant';content:string};
export default function Home(){
 const [user,setUser]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[files,setFiles]=useState<Attachment[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false);
 const input=useRef<HTMLInputElement>(null),end=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!supabase){setReady(true);return;} const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user.id??null);setReady(true);});return ()=>subscription.unsubscribe();},[]);
 useEffect(()=>{setMessages([]);setFiles([]);if(!user)return;try{const saved=JSON.parse(localStorage.getItem(`fyd:${user}`)||'[]');if(Array.isArray(saved))setMessages(saved.filter(m=>['user','assistant'].includes(m.role)&&typeof m.content==='string').slice(-100));}catch{setError('Could not restore saved conversation.');}},[user]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'});},[messages,busy]);
 function save(next:Message[]){setMessages(next);if(user)try{localStorage.setItem(`fyd:${user}`,JSON.stringify(next));}catch{setError('Device storage is full. Export your notes to keep them.');}}
 async function login(){if(!supabase){setError('Google sign-in needs setup. Follow the repository README.');return;} const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)setError(error.message);}
 async function select(selected:FileList|null){if(!selected)return;setError('');try{
  const loaded=await Promise.all(Array.from(selected).map(async file=>{if(file.size>MAX_FILE)throw Error('Each file must be under 2.8 MB.');return {name:file.name,type:file.type,data:await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(Error('Could not read file.'));r.readAsDataURL(file);})};}));
  validateAttachments(loaded);if(JSON.stringify(loaded).length>3_800_000)throw Error('Files together are too large. Keep the combined size below 2.8 MB.');setFiles(loaded);
 }catch(e){setError(e instanceof Error?e.message:'Could not read files.');}finally{if(input.current)input.current.value='';}}
 async function send(){if(busy||!question.trim())return;if(!user){await login();return;}setError('');setBusy(true);const next:Message[]=[...messages,{role:'user',content:question.trim()}];
 try{const session=await supabase!.auth.getSession();const payload=JSON.stringify({messages:next.slice(-20),files});if(new TextEncoder().encode(payload).length>MAX_BODY)throw Error('Message and attachments together are too large. Use smaller files.');
 const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.data.session?.access_token??''}`},body:payload});const result=await response.json();if(!response.ok)throw Error(result.error||'Could not complete the request.');save([...next,{role:'assistant',content:result.answer}]);setQuestion('');
 }catch(e){setError(e instanceof Error?e.message:'Connection failed. Please try again.');}finally{setBusy(false);}}
 function exportNotes(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob(['# FYD — For You Dillu\n\n'+messages.map(m=>`## ${m.role==='user'?'You':'FYD'}\n\n${m.content}`).join('\n\n')],{type:'text/markdown'}));a.href=url;a.download='FYD-study-notes.md';a.click();URL.revokeObjectURL(url);}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Leaf size={25}/></span><span>FYD<small>FOR YOU DILLU</small></span></a><button className="new-chat" disabled={busy} onClick={()=>{if(messages.length&&!confirm('Start a new chat? Export first if you want to keep these notes.'))return;save([]);setFiles([]);setError('');}}><Plus size={18}/> New study session</button><div className="nav-label">YOUR WORKSPACE</div><div className="nav-active"><Sparkles size={18}/> Study companion</div><button className="nav-button" onClick={exportNotes} disabled={!messages.length}><Download size={18}/> Export study notes</button><div className="sidebar-note"><BookOpen size={25}/><h3>A little progress, every day.</h3><p>Your space to understand, revise, and grow.</p></div><div className="account"><span className="avatar">D</span><div>Dillu’s study space<small>{user?'Google account connected':'Personal B.Pharmacy companion'}</small></div>{user&&<button aria-label="Sign out" disabled={busy} onClick={()=>supabase?.auth.signOut()}><LogOut size={17}/></button>}</div></aside>
 <main><header><div><span className="status-dot"/> Your personal study companion</div>{user?<span className="pill">B.Pharmacy</span>:<button className="login" disabled={!ready} onClick={login}>Sign in with Google</button>}</header><section className="conversation" aria-live="polite">{!messages.length?<div className="welcome"><div className="eyebrow"><Sparkles size={15}/> MADE FOR YOUR LEARNING JOURNEY</div><h1>A little clarity.<br/><em>A lot of possibility.</em></h1><p>Hi Dillu! Bring your questions, notes, and big ideas.<br/>Let’s make pharmacy a little easier, together.</p><div className="suggestions">{[['Understand a concept','Explain first-pass metabolism with an example.'],['Get exam ready','Create five revision questions about tablet manufacturing.'],['Make it simpler','Explain bioavailability in simple terms.']].map(([title,prompt])=><button key={title} onClick={()=>setQuestion(prompt)}><BookOpen size={20}/><strong>{title}</strong><span>{prompt}</span><span className="arrow">↗</span></button>)}</div></div>:messages.map((m,i)=><article key={i} className={`message ${m.role}`}><div className="message-author">{m.role==='user'?'YOU':'FYD · For You Dillu'}</div><Markdown>{m.content}</Markdown></article>)}{busy&&<div className="thinking">FYD is reading and thinking…</div>}<div ref={end}/></section>
 <div className="composer-wrap">{error&&<div role="alert" className="error">{error}</div>}{files.length>0&&<div className="attachments">{files.map(f=><span key={f.name}><FileText size={14}/>{f.name}</span>)}<button disabled={busy} onClick={()=>setFiles([])} aria-label="Remove attachments"><X size={16}/></button></div>}<form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="question">Your study question</label><textarea id="question" placeholder="Ask anything about your studies…" value={question} maxLength={12000} disabled={busy} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}}/><div className="composer-actions"><input ref={input} hidden type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple onChange={e=>void select(e.target.files)}/><button type="button" className="attach" disabled={busy} onClick={()=>input.current?.click()}><Paperclip size={18}/> Add PDF or images</button><button className="send" disabled={busy||!question.trim()} aria-label="Send question"><Send size={19}/></button></div></form><p className="footnote">1 complete PDF or up to 5 images · 2.8 MB combined · 30 requests/day, 300/month</p><p className="privacy">Attachments stay selected for follow-ups and are sent to the AI with each question. Study support; verify important facts with your textbooks.</p></div></main>
 <aside className="context"><div className="context-heading"><BookOpen size={19}/> Your study desk</div><div className="context-card"><span className="mini-label">A SPACE JUST FOR YOU</span><h2>Learn at your<br/>own pace.</h2><p>Upload your notes or a book PDF, then ask questions in your own words.</p><div className="book-art"><BookOpen size={70} strokeWidth={1}/><Leaf size={35}/></div></div><h3>How FYD helps</h3><ul><li>Clear explanations</li><li>Revision notes & practice questions</li><li>PDF and image understanding</li></ul><div className="local-note"><strong>Your notes, on this device</strong><p>Chat text is saved in this browser. Files remain in memory until you refresh or sign out. Export notes before clearing browser data.</p></div><small className="desk-footer">FOR YOU, DILLU. ALWAYS LEARNING.</small></aside></div>;
}
