'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, Plus, Send, Paperclip, X, Download, Leaf, Sparkles, LogOut, FileText } from 'lucide-react';
import Markdown from 'react-markdown';
import { supabase } from '../lib/browser';
import { useAuth, useClerk, UserButton } from '@clerk/nextjs';
type Doc={id:string;name:string;status:string;pages:number;processed:number;error?:string};
type Message={role:'user'|'assistant';content:string};
export default function Home(){
 const {userId:user,isLoaded:ready}=useAuth();const clerk=useClerk();
 const [messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[files,setFiles]=useState<Doc[]>([]),[library,setLibrary]=useState<Doc[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(''),[usage,setUsage]=useState({day_count:0,month_count:0}),[conversation,setConversation]=useState(''),[chats,setChats]=useState<{id:string;title:string}[]>([]);
 const input=useRef<HTMLInputElement>(null),end=useRef<HTMLDivElement>(null);
 async function api(path:string,body?:unknown){const r=await fetch('/api/study/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
 async function refresh(){const docs=await api('documents');setLibrary(docs);setFiles(old=>old.map(d=>docs.find((n:Doc)=>n.id===d.id)||d));setChats(await api('conversations'));setUsage(await api('usage'));}
 useEffect(()=>{setMessages([]);setFiles([]);setLibrary([]);setChats([]);setConversation(crypto.randomUUID());if(!user)return;let active=true;const tick=async()=>{try{const docs=await api('documents');if(active){setLibrary(docs);setFiles(old=>old.map(d=>docs.find((n:Doc)=>n.id===d.id)||d));}}catch(e){if(active)setError(e instanceof Error?e.message:'Could not load library');}};void tick();void api('usage').then(setUsage).catch(()=>{});void api('conversations').then(c=>{if(active)setChats(c);}).catch(()=>{});const timer=setInterval(tick,5000);return()=>{active=false;clearInterval(timer);};},[user]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'});},[messages,busy]);
 function save(next:Message[]){setMessages(next);if(next.length===0)setConversation(crypto.randomUUID());}
 async function login(){await clerk.openSignIn();}
 async function select(selected:FileList|null){if(!selected)return;if(!user){await login();return;}setError('');setBusy(true);try{
  const items=Array.from(selected);if(items.length>5||items.some(f=>f.type==='application/pdf')&&items.length!==1)throw Error('Choose one PDF or up to five images.');
  const uploaded:Doc[]=[];
  for(const file of items){if(file.size>20_000_000)throw Error('Each file must be under 20 MB.');if(!supabase)throw Error('Supabase storage needs configuration.');
   setProgress('Uploading '+file.name);const signed=await api('documents',{name:file.name,type:file.type,size:file.size});
   const {error:uploadError}=await supabase.storage.from('fyd-documents').uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type});if(uploadError)throw uploadError;
   await api('documents/'+signed.id+'/process',{});uploaded.push({id:signed.id,name:file.name,status:'queued',pages:0,processed:0});setFiles([...uploaded]);
  }await refresh();setProgress('Files queued. You can leave this page while they process.');
 }catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function send(){if(busy||!question.trim())return;if(!user){await login();return;}if(files.some(f=>f.status!=='ready')){setError('Wait for selected documents to finish processing.');return;}setError('');setBusy(true);try{const result=await api('chat',{question:question.trim(),documents:files.map(f=>f.id),conversation});setMessages(old=>[...old,{role:'user',content:question.trim()},{role:'assistant',content:result.answer}]);setQuestion('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Connection failed');}finally{setBusy(false);}}
 async function summary(doc:Doc){try{const result=await api('documents/'+doc.id+'/summary');if(result.status==='ready'){setMessages(old=>[...old,{role:'assistant',content:result.content}]);return;}if(result.status==='processing'||result.status==='queued'){setProgress('Summary is '+result.status+'. Click Summary again later to open it.');return;}await api('documents/'+doc.id+'/summary',{});setProgress('Whole-document summary queued. Click Summary again when it finishes.');}catch(e){setError(e instanceof Error?e.message:'Summary failed');}}
 function exportNotes(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob(['# FYD — For You Dillu\n\n'+messages.map(m=>`## ${m.role==='user'?'You':'FYD'}\n\n${m.content}`).join('\n\n')],{type:'text/markdown'}));a.href=url;a.download='FYD-study-notes.md';a.click();URL.revokeObjectURL(url);}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Leaf size={25}/></span><span>FYD<small>FOR YOU DILLU</small></span></a><button className="new-chat" disabled={busy} onClick={()=>{if(messages.length&&!confirm('Start a new chat? Export first if you want to keep these notes.'))return;save([]);setFiles([]);setError('');}}><Plus size={18}/> New study session</button><div className="nav-label">YOUR WORKSPACE</div><div className="nav-active"><Sparkles size={18}/> Study companion</div><button className="nav-button" onClick={exportNotes} disabled={!messages.length}><Download size={18}/> Export study notes</button><div className="sidebar-note"><BookOpen size={25}/><h3>A little progress, every day.</h3><p>Your space to understand, revise, and grow.</p></div><div className="account"><span className="avatar">D</span><div>Dillu’s study space<small>{user?'Account connected':'Personal B.Pharmacy companion'}</small></div>{user&&<button aria-label="Sign out" disabled={busy} onClick={()=>clerk.signOut()}><LogOut size={17}/></button>}</div></aside>
 <main><header><div><span className="status-dot"/> Your personal study companion</div>{user?<UserButton/>:<button className="login" disabled={!ready} onClick={login}>Sign in with Google</button>}</header><section className="conversation" aria-live="polite">{!messages.length?<div className="welcome"><div className="eyebrow"><Sparkles size={15}/> MADE FOR YOUR LEARNING JOURNEY</div><h1>A little clarity.<br/><em>A lot of possibility.</em></h1><p>Hi Dillu! Bring your questions, notes, and big ideas.<br/>Let’s make pharmacy a little easier, together.</p><div className="suggestions">{[['Understand a concept','Explain first-pass metabolism with an example.'],['Get exam ready','Create five revision questions about tablet manufacturing.'],['Make it simpler','Explain bioavailability in simple terms.']].map(([title,prompt])=><button key={title} onClick={()=>setQuestion(prompt)}><BookOpen size={20}/><strong>{title}</strong><span>{prompt}</span><span className="arrow">↗</span></button>)}</div></div>:messages.map((m,i)=><article key={i} className={`message ${m.role}`}><div className="message-author">{m.role==='user'?'YOU':'FYD · For You Dillu'}</div><Markdown>{m.content}</Markdown></article>)}{busy&&<div className="thinking">FYD is reading and thinking…</div>}<div ref={end}/></section>
 <div className="composer-wrap">{progress&&<p role="status">{progress}</p>}{error&&<div role="alert" className="error">{error}</div>}{files.length>0&&<div className="attachments">{files.map(f=><span key={f.name}><FileText size={14}/>{f.name} · {f.status} {f.pages?`${f.processed}/${f.pages}`:''}</span>)}<button disabled={busy} onClick={()=>setFiles([])} aria-label="Remove attachments"><X size={16}/></button></div>}<form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="question">Your study question</label><textarea id="question" placeholder="Ask anything about your studies…" value={question} maxLength={12000} disabled={busy} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}}/><div className="composer-actions"><input ref={input} hidden type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple onChange={e=>void select(e.target.files)}/><button type="button" className="attach" disabled={busy} onClick={()=>input.current?.click()}><Paperclip size={18}/> Add PDF or images</button><button className="send" disabled={busy||!question.trim()} aria-label="Send question"><Send size={19}/></button></div></form><p className="footnote">1 complete PDF or up to 5 images · 20 MB each · PDFs up to 500 pages</p><p className="privacy">Files are privately stored and processed page by page. {usage.day_count}/30 operations today · {usage.month_count}/300 this month. Verify important facts with your textbooks.</p></div></main>
 <aside className="context"><div className="context-heading"><BookOpen size={19}/> Your study desk</div><div className="context-card"><span className="mini-label">A SPACE JUST FOR YOU</span><h2>Learn at your<br/>own pace.</h2><p>Upload your notes or a book PDF, then ask questions in your own words.</p><div className="book-art"><BookOpen size={70} strokeWidth={1}/><Leaf size={35}/></div></div><h3>Your documents</h3><p>To preview a source, open Pages and enter its page number.</p><div className="document-list">{library.map(doc=><div key={doc.id} className="document-row"><label><input type="checkbox" disabled={busy||doc.status!=='ready'} checked={files.some(f=>f.id===doc.id)} onChange={e=>setFiles(old=>e.target.checked?[...old,doc].slice(-5):old.filter(f=>f.id!==doc.id))}/>{doc.name}</label><small>{doc.status} · {doc.processed}/{doc.pages} pages</small>{doc.error&&<small role="alert">{doc.error}</small>}{doc.status==='failed'&&<button onClick={()=>void api('documents/'+doc.id+'/retry',{}).then(refresh).catch(e=>setError(e.message))}>Retry</button>}{doc.status==='ready'&&<><button onClick={()=>void summary(doc)}>Summary</button><button onClick={()=>{const n=prompt('Page number','1');if(n&&/^\d+$/.test(n))void api('documents/'+doc.id+'/pages/'+n).then(p=>setMessages(old=>[...old,{role:'assistant',content:'### '+doc.name+' — page '+n+'\n\n'+p.text}])).catch(e=>setError(e.message));}}>Pages</button></>}{!['processing','deleting','queued_delete'].includes(doc.status)&&<button onClick={()=>{if(confirm('Permanently remove this document, extracted pages, summary and Cognee knowledge? Saved chat answers are retained.'))void api('documents/'+doc.id+'/delete',{}).then(refresh).catch(e=>setError(e.message));}}>Delete</button>}</div>)}</div><h3>Saved conversations</h3>{chats.map(c=><button className="history-button" key={c.id} disabled={busy} onClick={()=>void api('conversations/'+c.id).then(m=>{setConversation(c.id);setMessages(m);setFiles([]);}).catch(e=>setError(e.message))}>{c.title}</button>)}<h3>How FYD helps</h3><ul><li>Clear explanations</li><li>Revision notes & practice questions</li><li>PDF and image understanding</li></ul><div className="local-note"><strong>Your private study library</strong><p>Documents and chats are stored securely in your account. Select ready documents to use them in your next question.</p></div><small className="desk-footer">FOR YOU, DILLU. ALWAYS LEARNING.</small></aside></div>;
}
